### PR TITLE
Implement agnostic state saving for Oauth 2.0 backend

### PR DESCRIPTION
**Pull request by jaysonsantos**
This helps out when you run caddy in more than 1 instance to have HA, on the current code if you try to do it, it will return Unauthorized because the state lives in another process's memory.

This is still a work in progress, but I decided to submit the PR to hear what you think about and how to proceed with the tests, should I use a go implementation of memcached or use docker to spin up the service?

### CODE REVIEW

**Comment by greenpau** [comment]
@jaysonsantos , thank you for the PR! Please follow CONTRIBUTING.md

additionally, please add a doc as to how someone could/should use the updated state management.

**Comment by greenpau** [comment]
> about and how to proceed with the tests, should I use a go implementation of memcached or use docker to spin up the service?

@jaysonsantos , the go implementation works.

**Comment by jaysonsantos** [comment]
@greenpau would you take a new look please?

**Comment by greenpau** [comment]
> would you take a new look please?

@jaysonsantos , without going to deep into it, it looks good! I could see how this could be useful in other contexts. Could you please move the "state" package to "pkg" dir (one level up)?

**Comment by greenpau** [comment]
> Could you please move the "state" package to "pkg" dir (one level up)?

@jaysonsantos, scratch the above! 🤔 how about adding moving the code to `pkg/cache`? It is already something that I use to keep session cache.

**Comment by jaysonsantos** [comment]
@greenpau i just did it, check if that is what you wanted

**Comment by greenpau** [comment]
>  i just did it, check if that is what you wanted

@jaysonsantos, i meant moving files, e.g. `memcached.go` directly to `pkg/cache`, not `pkg/cache/state/memcached.go`.

Also, say I would want to use the same caching for other things. How would I name things that it would be either specific (e.g. `State` vs. `OauthState`) or generic (e.g. `Exists` vs `StateExists`).

```
// State stores the state of the OAuth2 flow.
type State interface {
	Init() error
	Add(state, nonce string) error
	Del(state string) error
	Exists(state string) (bool, error)
	ValidateNonce(state, nonce string) error
	AddCode(state, code string) error
}
```

**Comment by jaysonsantos** [comment]
hey @greenpau can you take another look on the new commit?
do you want to make the expiration times configurable? i searched for usages on those functions and nothing used them

**Comment by jaysonsantos** [comment]
note that i used memory cache for session and sandbox because i wanted to ask you where it is better to configure the global cache as it is used by other things as well

**Comment by greenpau** [comment]
@jaysonsantos, I spent time reviewing your PR today. Awesome work! 👍 Thank you so much!

Please let me know if you are at your final revision, and I will merge it.

> note that i used memory cache for session and sandbox because i wanted to ask you where it is better to configure the global cache as it is used by other things as well

Jayson, the reality is that this "cache" code really belongs to `jwt` plugin, as `https://github.com/greenpau/caddy-auth-jwt/tree/main/pkg/cache`, because, fundamentally, the `jwt` plugin is the "foundation" of auth portal.

Why it is important right now? The `jwt` plugin is not merely JWT-related. In fact, my plan is to change its name from `caddy-auth-jwt` to `caddy-authorize`. This would allow having multiple token technologies, fallback, oauth as part of authorization stack.

```
route /foo* {
  authorize {
    primary yes
    allow jwt paseto api_keys basic_auth
    order basic_auth paseto jwt api_keys
    ... etc ...
  }
}
```

I am planning to rename the plugin shortly. Will announce it on Twitter this week and do the migration the week after.

What do you think about moving some of the things in this PR to `caddy-authorize` (i.e. `caddy-auth-jwt`).

**Comment by jaysonsantos** [comment]
Hey there, IMO caching of JWT should not be JWT's permission as it should only know how to work with auth intrinsic, not the storage.
But, I'd even go a bit further and keep the signed session on the client side to avoid any kind of storage problems, mostly these types of sessions are not something secret but, just to be sure any kind of HMAC to sign it should be good enough.
Let me know your thoughts and I can change it accordinly.

**Comment by jaysonsantos** [comment]
Hey, what about the [global cache configuration](https://github.com/greenpau/caddy-auth-portal/pull/174/files#diff-78fc5009741edf4ee74bbec171d8266db878c19081d5a0f92783d801409c8f35R94-R96) (here it is only for oauth)? Or should I leave the [sandbox](https://github.com/greenpau/caddy-auth-portal/pull/174/files#diff-13bf95cb30bfcd0781476a78417d0d0ddfdb01ace24fe214b3d80c211a3b306eR72) and [session](https://github.com/greenpau/caddy-auth-portal/pull/174/files#diff-13bf95cb30bfcd0781476a78417d0d0ddfdb01ace24fe214b3d80c211a3b306eR62) as memory for now?

**Comment by jaysonsantos** [comment]
@greenpau I've implemented your suggestions [[from here](https://github.com/authp/authp.github.io/pull/1#discussion_r753670004) on [this commit](https://github.com/greenpau/caddy-auth-portal/pull/174/commits/f07e2fbffb42b3daa36e51477a42df77e466b636)

**Comment by greenpau** [comment]
@jaysonsantos ,my  apologies. this review needs to wait. Can't find time to sit down and review this in detail. Hopefully by the end/mid of December, but can't promise that.

**Comment by greenpau** [comment]
@jaysonsantos , please reopen in [github.com/greenpau/caddy-security](https://github.com/greenpau/caddy-security/issues/new/choose) if this is still relevant for you. Please consider sponsoring the work on the project! 👍 

Also, I think with the new setup, the caching could be the first class citizen.

```
security {
  authentication cache foo {
    server 1.2.3.4
  }
 
  authentication portal myportal {
    use foo for caching ...
```

**Pull request closed without merging**
