### PR TITLE
Implement AzureAD OAuth2 backend

### PR DESCRIPTION
**Pull request by cnschn**
As discussed in #64, this implements the Microsoft OAuth2 backend.

The actual implementation in `backend.go` is trivial, after making validation using the JWKs work by allowing empty/missing `alg` keys. I kept the modifications in `jwks.go` as minimal as possible, but I also noticed that the `Algorithm` field is not referenced anywhere in the code. In fact, after removing it entirely, all tests still pass and backends work, even those that do contain the `alg` key in their JWKs.

### CODE REVIEW

**Comment by greenpau** [comment]
@cnschn , thank you 👍 I will review it tomorrow.

**Review by greenpau — APPROVED** [review]

**Comment by greenpau** [comment]
@cnschn , actually, LGTM 👍 I guess once you understood the logic, it was easy to implement.

**Comment by greenpau** [comment]
@cnschn , thank you for the documentation 👍

**Comment by cnschn** [comment]
Great, glad I could contribute!

**Pull request merged**
